users:
  miyazaki:
    slack_userid: "U01EMP9T20P"
  yanaba:
    slack_userid: "U07UK5TBVG8"
  mitsudome:
    slack_userid: "U0A97BUCQDA"
  shima:
    slack_userid: "UMXD25S05"
  kent:
    slack_userid: "UFHS44D4G"
  sugimoto:
    slack_userid: "UD3CHJ6BT"
  obara:
    slack_userid: "U0A938E7C79"
